name: "Update Editor's Copy"

on:
  push:
    branches: [main]
    paths-ignore:
    - README.md
    - CONTRIBUTING.md
    - LICENSE.md
    - .gitignore
  pull_request:
    paths-ignore:
    - README.md
    - CONTRIBUTING.md
    - LICENSE.md
    - .gitignore

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    name: "Update Editor's Copy"
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: write
      pages: write
      pull-requests: write
    steps:
    - name: "Checkout"
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

    - name: "Setup"
      id: setup
      run: date -u "+date=%FT%T" >>"$GITHUB_OUTPUT"

    - name: "Caching"
      uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v5
      with:
        path: |
          .refcache
          .venv
          .gems
          node_modules
          .targets.mk
        key: i-d-${{ steps.setup.outputs.date }}
        restore-keys: i-d-

    - name: "Build Drafts"
      id: build
      uses: martinthomson/i-d-template@d2ce969b54014edf5671856b6866866c258bf8f5 # v1
      with:
        token: ${{ github.token }}

    - name: "Fix Lints"
      id: fix-lint
      if: always() && steps.build.outcome == 'failure'
      uses: martinthomson/i-d-template@d2ce969b54014edf5671856b6866866c258bf8f5 # v1
      with:
        make: fix-lint

    - name: "Propose Linting Fixes"
      if: >
        always() &&
        steps.fix-lint.outcome != 'skipped' &&
        github.event.pull_request &&
        github.event.pull_request.head.repo.full_name == github.repository
      uses: parkerbxyz/suggest-changes@2f6dfa025f552ae33ae42533057f3c6bee7d6537 # v3
      with:
        token: ${{ github.token }}

    - name: "Update GitHub Pages"
      uses: martinthomson/i-d-template@d2ce969b54014edf5671856b6866866c258bf8f5 # v1
      if: ${{ github.event_name == 'push' }}
      with:
        make: gh-pages
        token: ${{ github.token }}

    - name: "Archive Built Drafts"
      if: always()
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
      with:
        name: drafts
        retention-days: 90
        path: |
          draft-*.html
          draft-*.txt
